FROM golioth/golioth-ncs-base:v2.5.0-SDK-v0

# ARG NCS_VERSION=v2.5.0

SHELL ["nrfutil","toolchain-manager","launch","/bin/bash","--","-c"]
RUN \
  # mkdir app && mv west.yml app/ \
  # && west init -l app \
  # && west update --narrow -o=--depth=1 \
  # && west update \
  # && west zephyr-export \
  # && pip install -r deps/zephyr/scripts/requirements.txt
  # ls -al